# Generated by Django 2.0.5 on 2018-10-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesslog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(default=0)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', null=0)),
                ('url', models.CharField(default='', max_length=1024)),
                ('status_code', models.IntegerField(default=0)),
                ('access_time', models.DateTimeField()),
            ],
        ),
    ]
